### ISSUE TITLE
Move all formulations from PSI to HPS

### ISSUE THREAD

**Issue by jd-lara** [NREL-Sienna/HydroPowerSimulations.jl#15]
There are some remaining models and methods that can be moved to HPS once the first 0.1 release is ready.

**Comment by pesap** [comment]
Relevant files:
- hydro_generation.jl
- Everything that has Hydro on PowerSimulations.jl
- [Test in PSI](https://github.com/NREL-Sienna/PowerSimulations.jl/blob/main/test/test_device_hydro_generation_constructors.jl)
